#
# The used C++ compiler
CPP=g++

# Additional compilation flags
CPPFLAGS=-Wall -std=c++0x -O2 -march=native -m64 

#CPPFLAGS=-Wall -std=c++0x -O2 -march=native -m64 -fno-omit-frame-pointer

#CPPFLAGS=-Wall -std=c++0x -O2 -march=native -m64 -fno-omit-frame-pointer -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free
#CPPFLAGS=-Wall -std=c++0x -O2 -march=native -m64 -fPIC
#CPPFLAGS=-Wall -std=c++0x -m64 -g -ggdb -fno-omit-frame-pointer

####
#### External dependency configuration
####

# BOOST libraries

BOOST_DIR=/opt/boost
#BOOST_INCLUDE=/opt/boost/include/boost
BOOST_INCLUDE=-I/opt/boost/
BOOST_LIB=-lboost_serialization
#BOOST_LIB=-L/opt/boost/lib
#BOOST_TEST_LIB=/usr/lib/libboost_unit_test_framework.a -lboost_prg_exec_monitor
BOOST_TEST_LIB=/opt/boost/lib/libboost_unit_test_framework.a -lboost_prg_exec_monitor
##PERFTOOLS_LIB=-L/opt/google-perftools-1.6/lib -lprofiler -ltcmalloc

# Windows, boost 1.45, gcc 4.5
#BOOST_DIR=C:/Users/senowozi/dev/mingw/boost_1_45_0_64bit_452
#BOOST_INCLUDE=-I$(BOOST_DIR)/include/boost-1_45
#BOOST_LIB=$(BOOST_DIR)/lib/libboost_serialization-mgw45-mt-d.dll
#BOOST_LIB=$(BOOST_DIR)/lib/libboost_serialization-mgw45-mt-d-1_45.a
#BOOST_TEST_LIB=$(BOOST_DIR)/lib/libboost_test_exec_monitor-mgw45-mt-d-1_45.a
#BOOST_PO_LIB=$(BOOST_DIR)/lib/libboost_program_options-mgw45-mt-d-1_45.a

###
INCLUDE=$(BOOST_INCLUDE)

# default rule
%.o: %.cpp
	$(CPP) $(CPPFLAGS) $(INCLUDE) -c $^ -o $@

