
mex -g -output mex_vac -I../ mex_vac.cpp matlab_helpers.cpp ...
	-largeArrayDims ...
	-IC:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\include\boost-1_42 ...
	-LC:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib ...
	C:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib\libboost_serialization-vc90-mt-1_42.lib ...
	C:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib\libboost_math_c99-vc90-mt-1_42.lib ...
	C:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib\libboost_math_c99f-vc90-mt-1_42.lib ...
	C:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib\libboost_math_c99l-vc90-mt-1_42.lib ...
	C:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib\libboost_math_tr1-vc90-mt-1_42.lib ...
	C:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib\libboost_math_tr1f-vc90-mt-1_42.lib ...
	C:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\lib\libboost_math_tr1l-vc90-mt-1_42.lib ...
	-IC:\Users\senowozi\dev\msvc2008\boost_1_42_0_64bit\include\boost-1_42\boost\tr1 ...
	../Factor.cpp ../FactorGraph.cpp ../FactorGraphModel.cpp ../FactorType.cpp ...
	../FactorGraphStructurizer.cpp ../DisjointSet.cpp ../LogSumExp.cpp ../TreeInference.cpp ...
	../GibbsSampler.cpp ../FunctionMinimization.cpp ../FunctionMinimizationProblem.cpp ...
	../Likelihood.cpp ../InferenceMethod.cpp ../ParameterEstimationMethod.cpp ...
	../MaximumLikelihood.cpp ../FactorGraphObservation.cpp ../Prior.cpp ../NormalPrior.cpp ...
	../LaplacePrior.cpp ../MaximumPseudolikelihood.cpp ../FactorGraphUtility.cpp ...
	../Pseudolikelihood.cpp ../StudentTPrior.cpp ...
	../StructuredLossFunction.cpp ../StructuredHammingLoss.cpp ../StructuredSVM.cpp ...
	../StochasticFunctionMinimizationProblem.cpp ../StochasticFunctionMinimization.cpp ...
	../StructuredPerceptron.cpp ../RandomFactorGraphGenerator.cpp ...
	../VAcyclicDecomposition.cpp ../SubFactorGraph.cpp ...
	../FactorConditioningTable.cpp ../ConditionedFactorType.cpp ...
	../Conditioning.cpp ../MaximumCompositeLikelihood.cpp ...
	../TreeCoverDecomposition.cpp ../LinearProgrammingMAPInference.cpp ...
	../FactorDataSource.cpp ../BeliefPropagation.cpp ...
	../FactorGraphPartialObservation.cpp ...
	../RBFNetworkRegression.cpp ../RBFNetwork.cpp ../NonlinearRBFFactorType.cpp ...
	../GibbsInference.cpp ../StructuredMeanFieldInference.cpp ...
	../ExpectationMaximization.cpp ../RandomSource.cpp ../AISInference.cpp ...
	../SimulatedAnnealingInference.cpp ../MaximumCrissCrossLikelihood.cpp ...
	../DiffusionInference.cpp ../BruteForceExactInference.cpp ...
	../LinearFactorType.cpp ../ConstrainedFunctionMinimizationProblem.cpp ...
	../ConstrainedFunctionMinimization.cpp ../NaivePiecewiseTraining.cpp
